apiVersion: v1
kind: Pod
metadata:
  name: pod-a
spec:
  containers:
  - name: app-a
    image: nginx
    resources:
      requests:
        memory: "400Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
  - name: app-b
    image: nginx
    resources:
      requests:
        memory: "200Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
spec:
  containers:
  - name: app-c
    image: nginx
    resources:
      requests:
        memory: "400Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data:
  sample.csv: |
    column1,column2
    value1,value2
---
apiVersion: v1
kind: Pod
metadata:
  name: mediawiki-pod
spec:
  containers:
  - name: mediawiki
    image: mediawiki:latest
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    configMap:
      name: sample
